### ISSUE TITLE
How to pass custom attribute into the Node Graph?

### ISSUE THREAD

**Issue by Yorgg** [keijiro/VfxPyro#1]
Awesome project, thank you.
I am trying to add the color as a VFXEventAttribute, and access it in the node Graph. 

```
// OnMouseClick =>
_attrib = _vfx.CreateVFXEventAttribute();
_attrib.SetVector3("_color", color);
_vfx.SendEvent("OnManualSpawn", _attrib);
```

![image](https://user-images.githubusercontent.com/10824040/66260379-c9d55480-e772-11e9-9e48-ab53b12e9d05.png)

However this doesn't work.  Do you know what I am doing wrong here?

**Comment by keijiro** [comment]
You have to receive the color attribute using "Inherit Source Color" like done with "Inherit Source Position" to receive the position attribute in Initialize Particle context. In this case, you have to use the correct attribute name -- use `color` instead of `_color`.

**Comment by keijiro** [comment]
By the way, I'd recommend using forum instead of this issue tracker for general VFX questions like this one. I'm not very active on replying to questions due to the language barrier.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.
